[package]
name = "openhwp_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
aes.workspace = true
anyhow.workspace = true
cfb.workspace = true
flate2.workspace = true
insta.workspace = true
thiserror.workspace = true
