[package]
name = "hwpx"
version = "0.1.0"
edition = "2021"
description = "HWPX types and serialization/deserialization code"

[dependencies]
serde.workspace = true
quick-xml.workspace = true

[dev-dependencies]
insta.workspace = true
